import Link from "next/link";
import { notFound } from "next/navigation";
import { requireDeviceWorkflowContext } from "@/lib/devices/access";
import { getStudentDeviceIssueForStaff } from "@/lib/devices/data";
import { deviceTypeLabels, formatDateTimeInTimeZone, statusLabels } from "@/lib/devices/format";
import { issueStatusLabels, issueTypeLabels, validateIssueRequestId } from "@/lib/devices/issue-review";
import { IssueApprovalForm, IssueRejectionForm } from "./review-forms";
export const dynamic = "force-dynamic";
export default async function DeviceIssueDetailPage({ params }: { params: { requestId: string } }) {
  const context = await requireDeviceWorkflowContext(); const requestId = validateIssueRequestId(params.requestId); if (!requestId) notFound();
  const request = await getStudentDeviceIssueForStaff(context, requestId); if (!request) notFound();
  const timezone = context.currentSchool.timezone;
  const fields = [["Student", `${request.student_name}${request.student_number ? ` (${request.student_number})` : ""}`],["Residence", request.residence_name ?? "Unassigned"],["Device type", deviceTypeLabels[request.device_type]],["Manufacturer", request.manufacturer],["Model", request.model],["Color", request.color],["Serial number", request.serial_number ?? "Not set"],["Asset tag", request.asset_tag ?? "Not set"],["Current custody status", statusLabels[request.current_custody_status]],["Status at submission", statusLabels[request.device_status_at_submission]],["Request type", issueTypeLabels[request.request_type]],["Student reason", request.student_reason],["Submitted", formatDateTimeInTimeZone(request.submitted_at, timezone)]];
  const isAdmin = context.effectiveRole === "school_admin" || context.effectiveRole === "super_admin";
  const canShowApproval = request.request_type !== "disposal" || isAdmin;
  const behavior = request.request_type === "lost" ? "Approval marks the device Missing / Lost and creates a custody event. The approval note is optional." : request.request_type === "broken" ? "Approval records a damage exception. The current custody status remains unchanged and an approval note is required." : "Only a School Admin or eligible Super Admin may approve. The device must already be returned. Approval sets it Inactive; the QR value is preserved while public Device Pass access is revoked. An approval note is required.";
  return <div className="space-y-5"><header><p className="text-sm font-medium text-brand">Device Registry</p><h1 className="mt-1 text-2xl font-semibold">Issue request review</h1><p className="mt-2 text-sm text-neutral-600">Current status: <b>{issueStatusLabels[request.status]}</b></p></header><section className="rounded-lg border bg-white p-5"><dl className="grid gap-4 sm:grid-cols-2">{fields.map(([label,value])=><div key={label}><dt className="text-sm font-medium text-neutral-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{value}</dd></div>)}</dl></section>{request.status === "pending" ? <><p className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">{behavior}</p><div className="grid gap-4 md:grid-cols-2">{canShowApproval ? <IssueApprovalForm requestId={request.request_id} requestType={request.request_type}/> : <p className="rounded-lg border bg-neutral-50 p-4 text-sm text-neutral-600">Disposal approval is restricted to School Admin or eligible Super Admin.</p>}<IssueRejectionForm requestId={request.request_id}/></div></> : <section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Processed request detail</h2><p className="mt-2 text-sm">Result: {issueStatusLabels[request.status]}</p>{request.reviewed_at ? <p className="mt-1 text-sm">Reviewed: {formatDateTimeInTimeZone(request.reviewed_at, timezone)}</p> : null}{request.review_note ? <p className="mt-3 whitespace-pre-wrap text-sm">Staff feedback: {request.review_note}</p> : null}{request.resolution ? <p className="mt-2 text-sm">Resolution: {request.resolution.replaceAll("_", " ")}</p> : null}<Link className="mt-4 inline-flex font-semibold text-brand" href={`/app/devices/${request.device_id}`}>View device</Link></section>}<Link className="inline-flex min-h-11 items-center font-semibold text-brand" href="/app/devices/issues">Back to issue requests</Link></div>;
}
