"use client";
import { useFormState, useFormStatus } from "react-dom";
import { approveStudentDeviceIssueAction, rejectStudentDeviceIssueAction } from "@/lib/devices/issue-review-actions";
import type { DeviceIssueReviewActionState, DeviceIssueType } from "@/lib/devices/types";
const initial: DeviceIssueReviewActionState = { status: "idle", message: "" };
function Button({ children, reject = false }: { children: React.ReactNode; reject?: boolean }) { const { pending } = useFormStatus(); return <button className={`min-h-11 w-full rounded-md px-4 py-2 text-sm font-semibold text-white disabled:opacity-60 ${reject ? "bg-red-700" : "bg-brand"}`} disabled={pending}>{pending ? "Processing..." : children}</button>; }
function Error({ state }: { state: DeviceIssueReviewActionState }) { return state.status === "error" ? <p className="text-sm text-red-700" role="alert">{state.message}</p> : null; }
export function IssueApprovalForm({ requestId, requestType }: { requestId: string; requestType: DeviceIssueType }) { const [state, action] = useFormState(approveStudentDeviceIssueAction, initial); const required = requestType !== "lost"; return <form action={action} className="space-y-3 rounded-lg border p-4"><input name="requestId" type="hidden" value={requestId}/><label className="block text-sm font-medium">Approval note ({required ? "required" : "optional"})</label><textarea className="min-h-24 w-full rounded-md border p-3" maxLength={1000} name="reviewNote" required={required}/><Error state={state}/><Button>Approve request</Button></form>; }
export function IssueRejectionForm({ requestId }: { requestId: string }) { const [state, action] = useFormState(rejectStudentDeviceIssueAction, initial); return <form action={action} className="space-y-3 rounded-lg border border-red-200 p-4"><input name="requestId" type="hidden" value={requestId}/><label className="block text-sm font-medium">Reason for rejection (required)</label><textarea className="min-h-24 w-full rounded-md border p-3" maxLength={1000} name="reviewNote" required/><Error state={state}/><Button reject>Reject request</Button></form>; }
